version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/pkman92/wild-workouts-go-ddd-example"
  dependencies_vendored = true